"use client";

import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Home Page",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  const isAdmin = pathname.startsWith("/admin");
  const isAuth = pathname.startsWith("/auth/login");

  return (
    <html lang="en">
      <body>
        {/* Site Header (NOT for admin/auth) */}
        {!isAdmin && !isAuth && <Header />}

        {children}

        {/* Site Footer (NOT for admin/auth) */}
        {!isAdmin && !isAuth && <Footer />}
      </body>
    </html>
  );
}
